import pytest
from downscale.src.constants import (
    LARGEST_GROWTH,
    SAVED_BUCKET_EDGES,
    SIZE_CHANGE_VALUES,
    saved_percent_agg,
    size_change_clause,
)
from downscale.views import _build_must_list


def _source(value):
    return size_change_clause(value)["script"]["script"]["source"]


def _params(value):
    return size_change_clause(value)["script"]["script"].get("params", {})


def test_plain_smaller_and_larger_keep_their_old_meaning():
    assert "doc['new_size'].value < doc['original_size'].value" in _source(
        "smaller"
    )
    assert "doc['new_size'].value > doc['original_size'].value" in _source(
        "larger"
    )
    assert _params("smaller") == {}


@pytest.mark.parametrize("value", SIZE_CHANGE_VALUES)
def test_every_rung_excludes_unfinished_jobs(value):
    source = _source(value)

    assert "doc['new_size'].value > 0" in source
    assert "doc['original_size'].value > 0" in source


@pytest.mark.parametrize(
    "value, factor",
    [
        ("smaller_gt_5", 0.95),
        ("smaller_gt_10", 0.90),
        ("smaller_gt_20", 0.80),
        ("smaller_gt_30", 0.70),
        ("smaller_gt_50", 0.50),
        ("smaller_lt_5", 0.95),
        ("smaller_lt_10", 0.90),
    ],
)
def test_threshold_becomes_a_multiplier_on_the_original(value, factor):
    assert _params(value) == {"factor": pytest.approx(factor)}
    assert "params.factor" in _source(value)


def test_lt_and_gt_at_the_same_threshold_are_complementary():
    assert "<=" in _source("smaller_gt_5")
    assert ">" in _source("smaller_lt_5")
    assert "<=" not in _source("smaller_lt_5")


def test_rungs_reach_the_query_builder():
    [clause] = _build_must_list({"size_change": "smaller_gt_20"})

    assert clause == size_change_clause("smaller_gt_20")


def test_every_rung_has_a_band_to_count_it():
    thresholds = [
        int(value.rsplit("_", 1)[1])
        for value in SIZE_CHANGE_VALUES
        if value.startswith("smaller_")
    ]

    assert set(thresholds) <= set(SAVED_BUCKET_EDGES)


def test_unfinished_jobs_fall_outside_every_band():
    agg = saved_percent_agg()["range"]
    sentinel = int(agg["script"]["source"].split("return ")[1].split(";")[0])
    larger = next(r for r in agg["ranges"] if r["key"] == "larger")

    assert sentinel < LARGEST_GROWTH == larger["from"]
    assert all("from" in band for band in agg["ranges"])


def test_bands_are_contiguous_and_disjoint():
    agg = saved_percent_agg()["range"]
    bands = agg["ranges"]

    for lower, upper in zip(bands, bands[1:]):
        assert lower["to"] == upper["from"]

    assert "to" not in bands[-1]


def _evaluate(value: str, original: int, new: int) -> bool:
    script = size_change_clause(value)["script"]["script"]
    expression = script["source"]
    for painless, python in (
        ("doc['new_size'].size() > 0", "True"),
        ("doc['original_size'].size() > 0", "True"),
        ("doc['new_size'].value", str(new)),
        ("doc['original_size'].value", str(original)),
        ("params.factor", str(script.get("params", {}).get("factor"))),
        ("&&", "and"),
        ("!=", "!="),
    ):
        expression = expression.replace(painless, python)

    return eval(expression)  # noqa: S307 - generated by the code under test


@pytest.mark.parametrize(
    "original, new, expected",
    [
        (
            1000,
            500,
            {
                "smaller",
                "smaller_gt_5",
                "smaller_gt_10",
                "smaller_gt_20",
                "smaller_gt_30",
                "smaller_gt_50",
            },
        ),
        (1000, 960, {"smaller", "smaller_lt_5", "smaller_lt_10"}),
        (1000, 900, {"smaller", "smaller_gt_5", "smaller_gt_10"}),
        (1000, 1000, set()),
        (1000, 1020, {"larger"}),
        (1000, 2000, {"larger"}),
        (1000, 0, set()),
    ],
)
def test_which_rungs_a_job_actually_matches(original, new, expected):
    matched = {
        value
        for value in SIZE_CHANGE_VALUES
        if _evaluate(value, original, new)
    }

    assert matched == expected


@pytest.mark.parametrize("threshold", [5, 10])
def test_lt_rung_is_bounded_on_both_sides(threshold):
    assert _evaluate(f"smaller_lt_{threshold}", 1000, 999)
    assert not _evaluate(f"smaller_lt_{threshold}", 1000, 1001)
